In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create & Read

#### 1D Array

In [14]:
arr1 = np.array([1,2,3,4,5,6])

In [17]:
arr1

array([1, 2, 3, 4, 5, 6])

In [18]:
type(arr1)

numpy.ndarray

In [16]:
arr1.shape

(6,)

In [8]:
arr1.dtype

dtype('int32')

In [19]:
arr1.ndim

1

In [15]:
arr1.size

6

#### 2D Array

In [21]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 3)

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr2.size

6

#### 3D Array

In [32]:
arr3 = np.array([[[1,4,5],[6,7,4]], [[3,5,4],[5,8,7]], [[1,4,5],[6,7,4]]])

In [33]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [34]:
arr3.ndim

3

In [35]:
arr3.shape

(3, 2, 3)

In [36]:
arr3.size

18

## Create Random Array

In [37]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.6773206 , 0.03395653, 0.38617194],
        [0.65208587, 0.25910492, 0.85593819]],

       [[0.45285158, 0.36837384, 0.66567994],
        [0.079402  , 0.09800302, 0.68783352]],

       [[0.49082865, 0.61833145, 0.76593543],
        [0.85990102, 0.80915854, 0.39384172]]])

In [38]:
randomArr.dtype

dtype('float64')

In [39]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
zeros.ndim

3

In [43]:
full = np.full((3,2,3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [44]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [51]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [52]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [53]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [54]:
arr3[1][0][1]

5

In [55]:
arr3[1,0,1]

5

## Update & Delete

In [56]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [57]:
a1

array([[[0.58292612, 0.75527431],
        [0.42935058, 0.37138974],
        [0.69232269, 0.5915962 ]],

       [[0.93352009, 0.44351736],
        [0.46993973, 0.65247609],
        [0.97351544, 0.7629859 ]]])

In [58]:
a2

array([[[0.14136321, 0.24771471],
        [0.68704198, 0.0605764 ],
        [0.56135897, 0.57202464]],

       [[0.13893125, 0.49314418],
        [0.10630131, 0.15400581],
        [0.43690974, 0.7377092 ]]])

#### Basic Math Operations

In [59]:
np.add(a1,a2)

array([[[0.72428933, 1.00298902],
        [1.11639256, 0.43196614],
        [1.25368166, 1.16362085]],

       [[1.07245134, 0.93666154],
        [0.57624104, 0.80648189],
        [1.41042518, 1.5006951 ]]])

In [60]:
np.subtract(a1,a2)

array([[[ 0.44156291,  0.5075596 ],
        [-0.25769139,  0.31081334],
        [ 0.13096372,  0.01957156]],

       [[ 0.79458884, -0.04962682],
        [ 0.36363842,  0.49847028],
        [ 0.5366057 ,  0.02527669]]])

In [61]:
np.divide(a1,a2)

array([[[4.12360554, 3.04896834],
        [0.62492628, 6.13093146],
        [1.23329763, 1.03421454]],

       [[6.71929524, 0.89936652],
        [4.42082727, 4.23669801],
        [2.22818434, 1.03426376]]])

In [62]:
np.multiply(a1,a2)

array([[[0.08240431, 0.18709256],
        [0.29498187, 0.02249745],
        [0.38864155, 0.33840761]],

       [[0.12969511, 0.218718  ],
        [0.04995521, 0.10048511],
        [0.42533838, 0.56286172]]])

#### statistical operations

In [63]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [64]:
sqrt

5.0

In [65]:
abs

2

In [66]:
power

256

In [67]:
log

3.2188758248682006

In [68]:
mins

0.37138974020301085

In [69]:
maxs

0.7377092008969324

#### Update

In [70]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [71]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [72]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [73]:
#Reshape
arr3.shape

(3, 2, 3)

In [81]:
arr3_reshape = arr3.reshape(2,3,3)
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [82]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [83]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [84]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### insert

In [89]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [90]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [96]:
inserted_array = np.insert(zeros, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [97]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.58944286, 0.68843604, 0.07580459],
        [0.3117614 , 0.26083315, 0.93844093]],

       [[0.50825811, 0.69627414, 0.63986495],
        [0.61548673, 0.32246515, 0.38039329]],

       [[0.66090625, 0.67313811, 0.14735141],
        [0.53593431, 0.74478467, 0.20956469]]])

In [101]:
arr5 =np.delete(arr4, 0, axis=1)
arr5

array([[[0.3117614 , 0.26083315, 0.93844093]],

       [[0.61548673, 0.32246515, 0.38039329]],

       [[0.53593431, 0.74478467, 0.20956469]]])

In [102]:
np.save('new-array', arr5)

In [103]:
np.load('new-array.npy')

array([[[0.3117614 , 0.26083315, 0.93844093]],

       [[0.61548673, 0.32246515, 0.38039329]],

       [[0.53593431, 0.74478467, 0.20956469]]])